# Generated by Django 4.2.7 on 2023-11-12 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_rename_record_players_turns_players_fieldsize_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='fieldSize',
            field=models.PositiveSmallIntegerField(choices=[(16, '4x4'), (20, '5x5'), (36, '6x6')], default=16),
        ),
        migrations.AlterField(
            model_name='players',
            name='gameTime',
            field=models.CharField(default='Без таймера', max_length=100),
        ),
    ]
