# Generated by Django 4.2.7 on 2023-11-12 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_alter_players_fieldsize_alter_players_gametime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='players',
            name='gameTime',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
